---
site_name: Red Hat Partner Collection Certification
site_url: https://docs.ansible.com/projects/partner-certification/
repo_url: https://github.com/ansible/partner-certification
edit_uri: blob/main/docs/
docs_dir: docs
strict: true

theme:
  name: 'ansible'

nav:
  - Certification requirements:
      - index.md
      - Versioning: versioning.md
      - Ansible core compatibility: ansible-core-compatibility.md
      - Licensing: licensing.md
      - Project README: readmes.md
      - Changelogs: changelogs.md
      - Dependencies: dependencies.md
      - Sanity testing: sanity-testing.md
      - Static analysis: static-analysis.md
  - Certification tooling: tooling.md
