---
name: nox

"on":
  workflow_call:

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - session: spelling
            python-versions: "3.12"
          - session: formatters_check
            python-versions: "3.12"
          - session: commitlint
            python-versions: "3.12"
            fetch-depth: 0
          - session: build
            python-versions: "3.12"
    name: "Run nox ${{ matrix.session }} session"
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          fetch-depth: ${{ matrix.fetch-depth || 1 }}
          persist-credentials: false
      - name: Setup nox
        uses: wntrblm/nox@2026.04.10
        with:
          python-versions: "${{ matrix.python-versions }}"
      - name: "Run nox -e ${{ matrix.session }}"
        run: |
          nox -e "${{ matrix.session }}" -- ${{ matrix.extra-args }}
